apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: production
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080            # Port exposed internally in the cluster
      targetPort: 8080    # Port your Java app listens on
      nodePort: 30180       # External port exposed on the worker node (between 30000–32767)
  type: NodePort
